### ISSUE TITLE
Have to press next even though questions are on the same page

### ISSUE THREAD

**Issue by trishul5** [garydevenay/operationcovid19#23]
**Describe the solution you'd like**
Maybe, there could be an automatic slide to the next question

**Comment by eddiejaoude** [comment]
Is the next button even needed if on the same page?

**Comment by garydevenay** [comment]
I've changed this to wontfix at the moment. The next button acts as a form of step validation at the moment. There are no plans to change the validation method of the questionnaire at this point, but open to pull requests if this is a desired feature.
